from datetime import datetime
from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "cqK0Unkr9aYFcJLfHa5Y"

# Create the client instance
es = Elasticsearch(
    "https://localhost:9200",
    ca_certs="/Users/adhutsav/Downloads/elasticsearch-8.1.2/config/certs/http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

for idx in range(3):
    res = es.get(index="hashtags-tweets", id=idx)
    print(res['_source'])