from datetime import datetime
from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "cqK0Unkr9aYFcJLfHa5Y"

# Create the client instance
es = Elasticsearch(
    "https://localhost:9200",
    ca_certs="/Users/adhutsav/Downloads/elasticsearch-8.1.2/config/certs/http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

messages = [
        {'tweet' : 'This is positive Sentiment', 'sentiment' : 1},
        {'tweet' : 'This is negative sentiment', 'sentiment' : 2},
        {'tweet' : 'This is neutral sentiment', 'sentiment': 0}
]

for idx,message in enumerate(messages):
    res = es.index(index='hashtags-tweets', id = idx, document = message)
    print(res['result'])

